name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        key: cargo-cache
        path: ~/.cargo/registry
    - name: Formatter
      run: cargo fmt -- --check
    - name: Typecheck
      run: cargo check
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check whether history is semilinear
      run: ./semilinear_history.sh
